### ISSUE TITLE
Document how to add/edit system files

### ISSUE THREAD

**Issue by jmgilman** [ublue-os/image-template#18]
The README says it demonstrates how to:

> modify system files (like /etc/systemd/system.conf)

However, I don't see where this is happening, and adding it is not apparent. Was this an oversight or am I missing something?

**Comment by noelmiller** [comment]
We removed this example due to changes in F40. I will remove that from the README.

**Comment by jmgilman** [comment]
> We removed this example due to changes in F40. I will remove that from the README.

Is there something preventing me from doing this? From what I've gathered, you need to `COPY` into the container to where you want the file to be on the system. Having a simple example of that may still be useful to clarify it.

**Comment by noelmiller** [comment]
> > We removed this example due to changes in F40. I will remove that from the README.
> 
> Is there something preventing me from doing this? From what I've gathered, you need to `COPY` into the container to where you want the file to be on the system. Having a simple example of that may still be useful to clarify it.

This was the initial example: https://github.com/ublue-os/image-template/issues/10 This would require some silly if logic to get it to work on both F39 and F40 since they changed the location of these files. We found it was too complicated of an example for someone to grok as an initial starting point.
